services:
  # Backend API Service
  - type: web
    name: electricity-record-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@power.local
      - key: ADMIN_PASSWORD
        value: Admin@1234
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: static
    name: electricity-record-frontend
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://electricity-record-api.onrender.com
